# Site settings
title: 한국독립게임마당
email: indiegameyard@gmail.com
url: https://indiegameyard.github.io
description: "한국독립게임마당 공식 누리집에 오신 것을 환영합니다."
repository: IndieGameYard/IndieGameYard.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: IndieGameYard

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://www.twitter.com/indiegamekorea
  - title: facebook
    url: https://www.facebook.com/indiegameyard
  - title: github
    url: https://www.github.com/IndieGameYard

# Build settings
markdown: kramdown
permalink: pretty
